#!/usr/bin/env python3
"""
Route Definitions: CRM Integration Routes
Exposes REST endpoints for CRM ingestion: fetching leads, call transcripts, and agent metrics.
Tags: CRM Integration
Prefix: /api/crm/v1
"""

import logging
import datetime
import re
from typing import List, Dict, Any, Optional
from fastapi import APIRouter, HTTPException, Header, Query, Path, status
from pydantic import BaseModel, Field
from bson import ObjectId

from core.mongo_manager import mongo_db
from routes.agent_routes import find_agent_by_id_and_enterprise, build_enterprise_or_conditions, bson_safe
from core.agent_resolver import resolve_agent_config

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/api/crm/v1",
    tags=["CRM Integration"],
    responses={
        401: {"description": "Unauthorized Access - Bearer token or Enterprise ID missing"},
        404: {"description": "Resource Not Found"},
        500: {"description": "Internal Server Error"}
    }
)

# Synthetic priming text injected as a fake first "user" turn to kick off the
# model's greeting (see core/modular_sales_bot.py) — no human ever said this,
# so it must never reach a transcript UI as if the customer/agent said it.
_SYNTHETIC_PRIMING_MESSAGES = {
    "We just called the customer.",
    "A customer just called our sales line. Please greet them warmly and ask how you can help them today.",
}


def clean_transcript(transcript):
    """Strip injected RAG context and synthetic priming turns; drop system/tool action entries."""
    if not isinstance(transcript, list):
        return transcript
    cleaned = []
    for msg in transcript:
        if not isinstance(msg, dict):
            cleaned.append(msg)
            continue
        text = msg.get("msg")
        if not isinstance(text, str):
            cleaned.append(msg)
            continue
        if text.startswith('[Requested action:') or text.startswith('[Action output:'):
            continue
        if text.strip() in _SYNTHETIC_PRIMING_MESSAGES:
            continue
        text = re.sub(r'\n\n\[Relevant Knowledge Base Context:.*?\]', '', text, flags=re.DOTALL)
        msg["msg"] = text.strip()
        cleaned.append(msg)
    return cleaned


def parse_date_to_timestamp(date_str: str, is_end_of_day: bool = False) -> float | None:
    """Helper to parse 'YYYY-MM-DD' or ISO date strings to UNIX timestamp float."""
    if not date_str or not str(date_str).strip():
        return None
    ds = str(date_str).strip()
    try:
        if len(ds) == 10 and ds.count("-") == 2:
            if is_end_of_day:
                dt = datetime.datetime.strptime(f"{ds} 23:59:59", "%Y-%m-%d %H:%M:%S")
            else:
                dt = datetime.datetime.strptime(f"{ds} 00:00:00", "%Y-%m-%d %H:%M:%S")
            return dt.timestamp()
        dt = datetime.datetime.fromisoformat(ds.replace("Z", "+00:00"))
        return dt.timestamp()
    except Exception as e:
        logger.warning(f"Failed to parse date string '{date_str}': {e}")
        return None


@router.get(
    "/agents/{agentId}/leads",
    status_code=status.HTTP_200_OK,
    summary="Fetch all leads (CRM Integration)",
    description="Retrieve a clean list of leads generated by an AI agent for ingestion into a CRM system."
)
async def get_crm_agent_leads(
    agentId: str = Path(..., description="The unique ID of the AI Agent (agentId string or Mongo _id)"),
    startDate: Optional[str] = Query(None, description="Filter leads starting from this date (e.g., 2026-05-01)"),
    endDate: Optional[str] = Query(None, description="Filter leads up to this date (e.g., 2026-05-31)"),
    page: int = Query(1, ge=1, description="Page number for pagination"),
    limit: int = Query(50, ge=1, le=500, description="Number of leads per page"),
    enterprise_id: Optional[str] = Query(None, description="Enterprise ID query parameter"),
    direction: Optional[str] = Query(None, description="Filter by call direction: 'inbound' or 'outbound'"),
    x_enterprise_id: Optional[str] = Header(None, alias="x-enterprise-id", description="Enterprise ID header")
):
    ent_id = (enterprise_id or x_enterprise_id or "").strip()
    
    if mongo_db.client is None:
        return {"success": True, "total": 0, "page": page, "limit": limit, "leads": []}
        
    db = mongo_db.client.get_default_database()
    
    target_ids = [agentId]
    resolved_agent = await find_agent_by_id_and_enterprise(agentId, ent_id) if ent_id else await resolve_agent_config(agentId)
    if ent_id and not resolved_agent:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"success": False, "message": f"Agent '{agentId}' not found for enterprise '{ent_id}'"}
        )
    if resolved_agent:
        if resolved_agent.get("agentId"):
            target_ids.append(resolved_agent.get("agentId"))
        if resolved_agent.get("_id"):
            target_ids.append(str(resolved_agent.get("_id")))
            
    start_ts = parse_date_to_timestamp(startDate, is_end_of_day=False)
    end_ts = parse_date_to_timestamp(endDate, is_end_of_day=True)
    
    agent_clauses = []
    for tid in set(target_ids):
        agent_clauses.extend([
            {"agentId": tid},
            {"agent_id": tid},
            {"agent": tid},
            {"agent_mongo_id": tid}
        ])
        if ObjectId.is_valid(tid):
            agent_clauses.append({"_id": ObjectId(tid)})

    # Also pull logs by enterprise_id (covers records saved without an agent_id)
    resolved_enterprise = ent_id or (resolved_agent.get("enterprise") or resolved_agent.get("createdBy") or "" if resolved_agent else "")
    if resolved_enterprise:
        for eid_key in ("enterprise_id", "enterprise", "company_id", "createdBy"):
            agent_clauses.append({eid_key: resolved_enterprise})

    filt = {"$or": agent_clauses} if agent_clauses else {}

    leads_map = {}
    target_collections = ["Agent_Stream_CallsLogs", "outbound_calls", "aiagentcallreports"]
    
    for coll_name in target_collections:
        try:
            cursor = db[coll_name].find(filt)
            async for doc in cursor:
                doc_id = str(doc["_id"])
                if doc_id in leads_map:
                    continue
                    
                ts = doc.get("timestamp") or doc.get("createdAt") or doc.get("created_at") or 0
                ts_val = 0.0
                if isinstance(ts, (int, float)):
                    ts_val = float(ts)
                elif isinstance(ts, str):
                    try:
                        ts_val = datetime.datetime.fromisoformat(ts.replace("Z", "+00:00")).timestamp()
                    except Exception:
                        ts_val = 0.0
                elif isinstance(ts, datetime.datetime):
                    ts_val = ts.timestamp()
                    
                if start_ts is not None and ts_val < start_ts:
                    continue
                if end_ts is not None and ts_val > end_ts:
                    continue

                # outbound_calls docs are always outbound campaign calls by definition
                # (no "direction" field needed); everything else falls back to its own
                # "direction" field, defaulting to inbound when absent.
                is_outbound = coll_name == "outbound_calls" or str(doc.get("direction", "")).lower() == "outbound"
                if direction and direction.strip().lower() in ("inbound", "outbound"):
                    wants_outbound = direction.strip().lower() == "outbound"
                    if is_outbound != wants_outbound:
                        continue

                phone = doc.get("virtualNumber") or doc.get("phone_number") or doc.get("caller_phone_no") or doc.get("lead_phone_no") or doc.get("to_number") or doc.get("from_number") or ""
                name = doc.get("customer_name") or doc.get("name") or doc.get("lead_name") or "Customer"
                email = doc.get("email") or doc.get("lead_email") or ""
                summary = doc.get("call_summary") or doc.get("summary") or ""
                meeting_consent = doc.get("caller_meeting_consent") or doc.get("meeting_consent") or False
                business_interest = doc.get("business_interest") or doc.get("car_model") or ""
                transcript = clean_transcript(doc.get("transcript") or doc.get("messages") or doc.get("conversation") or [])
                raw_call_id = str(doc.get("call_id") or doc.get("call_sid") or doc_id).strip()
                call_key = raw_call_id.split("@")[0].strip()
                status_str = doc.get("status", "completed")
                # duration_seconds is always numeric; "duration" is a display
                # string like "232.5s" (see analytics_manager.py) that used to
                # win here since it's checked first and always truthy — the
                # frontend's Math ops then evaluated "232s" as NaN. Prefer the
                # numeric field, and defensively coerce whatever we do get.
                raw_duration = doc.get("duration_seconds")
                if raw_duration is None:
                    raw_duration = doc.get("duration")
                if isinstance(raw_duration, str):
                    try:
                        raw_duration = float(raw_duration.rstrip("sS").strip())
                    except (ValueError, AttributeError):
                        raw_duration = 0
                duration = raw_duration or 0
                
                lead_entry = {
                    "id": doc_id,
                    "conversationId": call_key,
                    "agentId": agentId,
                    "enterpriseId": ent_id or doc.get("enterprise_id") or doc.get("enterprise"),
                    "name": name,
                    "phone": phone,
                    "email": email,
                    "summary": summary,
                    "meetingConsent": bool(meeting_consent),
                    "businessInterest": business_interest,
                    "status": status_str,
                    "durationSeconds": duration,
                    "timestamp": ts.strftime('%Y-%m-%dT%H:%M:%S.%f') + "+05:30" if isinstance(ts, datetime.datetime) else ts,
                    "transcript": transcript,
                    "direction": "outbound" if is_outbound else "inbound",
                    "campaignId": doc.get("campaign_id") or doc.get("context", {}).get("campaign_id"),
                    "campaignName": doc.get("campaign_name") or doc.get("context", {}).get("campaign_name"),
                }
                
                if call_key in leads_map:
                    existing = leads_map[call_key]
                    if not existing.get("transcript") and transcript:
                        existing["transcript"] = transcript
                    if not existing.get("summary") and summary:
                        existing["summary"] = summary
                    if existing.get("status") in ["initiated", "queued"] and status_str not in ["initiated", "queued"]:
                        existing["status"] = status_str
                    if not existing.get("durationSeconds") and duration:
                        existing["durationSeconds"] = duration
                    if not existing.get("phone") and phone:
                        existing["phone"] = phone
                else:
                    leads_map[call_key] = lead_entry
        except Exception as ex:
            logger.warning(f"Error querying collection '{coll_name}' for leads: {ex}")
            
    all_leads = list(leads_map.values())
    
    def get_ts(item):
        t = item.get("timestamp") or 0
        if isinstance(t, (int, float)):
            return float(t)
        if isinstance(t, str):
            try:
                return datetime.datetime.fromisoformat(t.replace("Z", "+00:00")).timestamp()
            except Exception:
                return 0.0
        return 0.0
        
    all_leads.sort(key=get_ts, reverse=True)
    total_count = len(all_leads)
    skip = (page - 1) * limit
    paginated_leads = all_leads[skip : skip + limit]
    
    return {
        "success": True,
        "total": total_count,
        "page": page,
        "limit": limit,
        "leads": paginated_leads
    }


@router.get(
    "/agents/conversations/{conversationId}/transcript",
    status_code=status.HTTP_200_OK,
    summary="Fetch call transcript (CRM Integration)",
    description="Retrieve the full transcript of a specific call by its conversationId."
)
async def get_crm_call_transcript(
    conversationId: str = Path(..., description="The unique conversation ID of the call (call_id, call_sid, or Mongo _id)"),
    enterprise_id: Optional[str] = Query(None, description="Enterprise ID query parameter"),
    x_enterprise_id: Optional[str] = Header(None, alias="x-enterprise-id", description="Enterprise ID header")
):
    if mongo_db.client is None:
        raise HTTPException(status_code=500, detail={"success": False, "message": "Database connection error"})
        
    db = mongo_db.client.get_default_database()
    
    id_clauses = [
        {"call_id": {"$regex": f"^{conversationId}"}},
        {"callId": {"$regex": f"^{conversationId}"}},
        {"call_sid": conversationId},
        # Links an outbound campaign's Exotel call_sid (from outbound_calls) directly to the
        # transcript log written by the bridged SIP leg — see modular_sales_bot.py's
        # "outbound_call_sid" session field.
        {"outbound_call_sid": conversationId},
        {"_id": conversationId}
    ]
    if ObjectId.is_valid(conversationId):
        id_clauses.append({"_id": ObjectId(conversationId)})
        
    query = {"$or": id_clauses}

    target_collections = ["Agent_Stream_CallsLogs", "outbound_calls", "aiagentcallreports"]
    logger.info(f"DEBUG TRANSCRIPT QUERY: {query}")
    outbound_anchor = None  # remembers the outbound_calls doc if matched but transcript is empty
    _debug_fallback = None
    for coll_name in target_collections:
        try:
            doc = await db[coll_name].find_one(query)
            logger.info(f"DEBUG TRANSCRIPT RESULT for {coll_name}: {'FOUND' if doc else 'NOT FOUND'}")
            if doc:
                transcript = clean_transcript(doc.get("transcript", []))
                if transcript:
                    safe_doc = bson_safe(dict(doc))
                    safe_doc["_id"] = str(safe_doc["_id"])
                    safe_doc["transcript"] = transcript
                    return {
                        "success": True,
                        "conversationId": conversationId,
                        "transcript": safe_doc["transcript"],
                        "call_details": safe_doc
                    }
                # Matched by call_sid but the bridged SIP leg never linked its own
                # conversation doc back to this outbound call (see modular_sales_bot.py's
                # phone-matching fallback failing when the bridged leg reports the
                # agent's own virtual number instead of the customer's). Keep this doc as
                # an anchor (timestamp/agent_id/enterprise_id) and fall back below to the
                # nearest real conversation doc for the same agent instead of returning empty.
                if coll_name == "outbound_calls":
                    outbound_anchor = doc
        except Exception as ex:
            logger.warning(f"Error querying collection '{coll_name}' for transcript: {ex}")

    if outbound_anchor is not None:
        anchor_ts = outbound_anchor.get("timestamp") or 0
        anchor_agent = outbound_anchor.get("agent_id") or outbound_anchor.get("context", {}).get("agent_id")
        anchor_ent = outbound_anchor.get("enterprise_id") or outbound_anchor.get("context", {}).get("enterprise_id")
        if anchor_ts and anchor_agent:
            # NOTE: outbound_calls.timestamp is a numeric epoch, but
            # Agent_Stream_CallsLogs/aiagentcallreports store timestamp as an ISO
            # string — a numeric Mongo range query on that field matches nothing
            # across collections with mixed types, so filter by agent only in
            # Mongo and do the time-window comparison in Python instead.
            agent_query = {
                "$or": [
                    {"agentId": anchor_agent}, {"agent_id": anchor_agent},
                    {"agent_mongo_id": anchor_agent}
                ]
            }
            if anchor_ent:
                agent_query = {
                    "$and": [
                        agent_query,
                        {"$or": [
                            {"enterprise_id": anchor_ent}, {"enterprise": anchor_ent},
                            {"enterpriseId": anchor_ent}
                        ]}
                    ]
                }

            IST = datetime.timezone(datetime.timedelta(hours=5, minutes=30))

            def _to_epoch(ts):
                if isinstance(ts, (int, float)):
                    return float(ts)
                if isinstance(ts, str):
                    try:
                        return datetime.datetime.fromisoformat(ts.replace("Z", "+00:00")).timestamp()
                    except Exception:
                        return None
                if isinstance(ts, datetime.datetime):
                    # Stored as a naive datetime representing IST wall-clock time (see
                    # bson_safe's "+05:30" formatting elsewhere in this codebase). Calling
                    # .timestamp() on a naive datetime silently assumes the SYSTEM's local
                    # timezone, not IST — on a UTC-clocked server this shifts every
                    # conversion by 5.5 hours, which was pushing every real match outside
                    # the fallback's time window. Attach IST explicitly instead.
                    if ts.tzinfo is None:
                        ts = ts.replace(tzinfo=IST)
                    return ts.timestamp()
                return None

            best_doc = None
            best_diff = None
            _debug_fallback = {"agent_query": agent_query, "collections": {}}
            for coll_name in ("Agent_Stream_CallsLogs", "aiagentcallreports"):
                _cinfo = {"scanned": 0, "in_window": 0, "with_transcript": 0, "error": None}
                try:
                    cursor = db[coll_name].find(agent_query).sort("_id", -1).limit(50)
                    async for cand in cursor:
                        _cinfo["scanned"] += 1
                        cand_epoch = _to_epoch(cand.get("timestamp"))
                        if cand_epoch is None or not (anchor_ts - 30 <= cand_epoch <= anchor_ts + 600):
                            continue
                        _cinfo["in_window"] += 1
                        cand_transcript = clean_transcript(cand.get("transcript", []))
                        if not cand_transcript:
                            continue
                        _cinfo["with_transcript"] += 1
                        diff = abs(cand_epoch - anchor_ts)
                        if best_diff is None or diff < best_diff:
                            best_doc = (coll_name, cand)
                            best_diff = diff
                except Exception as ex:
                    _cinfo["error"] = str(ex)
                    logger.warning(f"Error querying collection '{coll_name}' for transcript fallback: {ex}")
                _debug_fallback["collections"][coll_name] = _cinfo

            if best_doc is not None:
                coll_name, cand = best_doc
                safe_doc = bson_safe(dict(cand))
                safe_doc["_id"] = str(safe_doc["_id"])
                safe_doc["transcript"] = clean_transcript(cand.get("transcript", []))
                logger.info(
                    f"DEBUG TRANSCRIPT FALLBACK: matched conversationId '{conversationId}' "
                    f"to nearby conversation doc '{safe_doc['_id']}' in {coll_name} via time-window fallback."
                )
                return {
                    "success": True,
                    "conversationId": conversationId,
                    "transcript": safe_doc["transcript"],
                    "call_details": safe_doc
                }

    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail={"success": False, "message": f"Transcript for conversationId '{conversationId}' not found"}
    )


@router.get(
    "/agents/{agentId}/metrics",
    status_code=status.HTTP_200_OK,
    summary="Fetch agent metrics (CRM Integration)",
    description="Retrieve high-level analytics like total calls, average duration, and business interest distributions for a given date range."
)
async def get_crm_agent_metrics(
    agentId: str = Path(..., description="The unique ID of the AI Agent"),
    startDate: Optional[str] = Query(None, description="Filter starting from this date (e.g., 2026-05-01)"),
    endDate: Optional[str] = Query(None, description="Filter up to this date (e.g., 2026-05-31)"),
    enterprise_id: Optional[str] = Query(None, description="Enterprise ID query parameter"),
    direction: Optional[str] = Query(None, description="Filter by call direction: 'inbound' or 'outbound'"),
    x_enterprise_id: Optional[str] = Header(None, alias="x-enterprise-id", description="Enterprise ID header")
):
    ent_id = (enterprise_id or x_enterprise_id or "").strip()
    
    if mongo_db.client is None:
        return {"success": True, "agentId": agentId, "metrics": {}}
        
    db = mongo_db.client.get_default_database()
    
    target_ids = [agentId]
    resolved_agent = await find_agent_by_id_and_enterprise(agentId, ent_id) if ent_id else await resolve_agent_config(agentId)
    if ent_id and not resolved_agent:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"success": False, "message": f"Agent '{agentId}' not found for enterprise '{ent_id}'"}
        )
    if resolved_agent:
        if resolved_agent.get("agentId"):
            target_ids.append(resolved_agent.get("agentId"))
        if resolved_agent.get("_id"):
            target_ids.append(str(resolved_agent.get("_id")))
            
    start_ts = parse_date_to_timestamp(startDate, is_end_of_day=False)
    end_ts = parse_date_to_timestamp(endDate, is_end_of_day=True)
    
    agent_clauses = []
    for tid in set(target_ids):
        agent_clauses.extend([
            {"agentId": tid},
            {"agent_id": tid},
            {"agent": tid},
            {"agent_mongo_id": tid}
        ])
        if ObjectId.is_valid(tid):
            agent_clauses.append({"_id": ObjectId(tid)})

    # Also pull logs by enterprise_id (covers records saved without an agent_id)
    resolved_enterprise = ent_id or (resolved_agent.get("enterprise") or resolved_agent.get("createdBy") or "" if resolved_agent else "")
    if resolved_enterprise:
        for eid_key in ("enterprise_id", "enterprise", "company_id", "createdBy"):
            agent_clauses.append({eid_key: resolved_enterprise})

    filt = {"$or": agent_clauses} if agent_clauses else {}

    seen_ids = set()
    total_calls = 0
    completed_calls = 0
    failed_calls = 0
    total_duration_sec = 0.0
    business_interests = {}
    languages_dist = {}
    day_wise = {}  # date str (YYYY-MM-DD) -> { count, seconds, <business_interest>: count }

    target_collections = ["Agent_Stream_CallsLogs", "outbound_calls", "aiagentcallreports"]
    for coll_name in target_collections:
        try:
            cursor = db[coll_name].find(filt)
            async for doc in cursor:
                doc_id = str(doc["_id"])
                if doc_id in seen_ids:
                    continue
                seen_ids.add(doc_id)

                ts = doc.get("timestamp") or doc.get("createdAt") or doc.get("created_at") or 0
                ts_val = 0.0
                if isinstance(ts, (int, float)):
                    ts_val = float(ts)
                elif isinstance(ts, str):
                    try:
                        ts_val = datetime.datetime.fromisoformat(ts.replace("Z", "+00:00")).timestamp()
                    except Exception:
                        ts_val = 0.0
                elif isinstance(ts, datetime.datetime):
                    ts_val = ts.timestamp()

                if start_ts is not None and ts_val < start_ts:
                    continue
                if end_ts is not None and ts_val > end_ts:
                    continue

                is_outbound = coll_name == "outbound_calls" or str(doc.get("direction", "")).lower() == "outbound"
                if direction and direction.strip().lower() in ("inbound", "outbound"):
                    wants_outbound = direction.strip().lower() == "outbound"
                    if is_outbound != wants_outbound:
                        continue

                total_calls += 1
                status_str = str(doc.get("status", "completed")).lower()
                if status_str in ["completed", "success", "answered"]:
                    completed_calls += 1
                else:
                    failed_calls += 1

                # Same duration_seconds-vs-"duration" string bug as the leads
                # endpoint above — "duration" can be "232.5s", which float()
                # raises on, silently aborting the rest of this collection's
                # loop (caught by the broad except below). Prefer the numeric
                # field and defensively parse the string as a fallback.
                raw_duration = doc.get("duration_seconds")
                if raw_duration is None:
                    raw_duration = doc.get("duration")
                if isinstance(raw_duration, str):
                    try:
                        raw_duration = float(raw_duration.rstrip("sS").strip())
                    except (ValueError, AttributeError):
                        raw_duration = 0
                duration = float(raw_duration or 0)
                total_duration_sec += duration

                b_interest = doc.get("business_interest") or doc.get("car_model") or "General"
                business_interests[b_interest] = business_interests.get(b_interest, 0) + 1

                lang = doc.get("language") or "en"
                if isinstance(lang, list) and lang:
                    lang = lang[0]
                languages_dist[str(lang)] = languages_dist.get(str(lang), 0) + 1

                if ts_val > 0:
                    day_key = datetime.datetime.fromtimestamp(ts_val).strftime("%Y-%m-%d")
                    day_entry = day_wise.setdefault(day_key, {"date": day_key, "count": 0, "seconds": 0.0})
                    day_entry["count"] += 1
                    day_entry["seconds"] += duration
                    day_entry[b_interest] = day_entry.get(b_interest, 0) + 1
        except Exception as ex:
            logger.warning(f"Error computing metrics from '{coll_name}': {ex}")

    avg_duration = round(total_duration_sec / total_calls, 2) if total_calls > 0 else 0.0
    total_minutes = round(total_duration_sec / 60.0, 2)
    day_wise_list = sorted(day_wise.values(), key=lambda d: d["date"])

    return {
        "success": True,
        "agentId": agentId,
        "enterpriseId": ent_id,
        "metrics": {
            "totalCalls": total_calls,
            "completedCalls": completed_calls,
            "failedCalls": failed_calls,
            "totalDurationMinutes": total_minutes,
            "averageDurationSeconds": avg_duration,
            "businessInterests": business_interests,
            "languages": languages_dist,
            "dayWise": day_wise_list
        }
    }
